
title: Noble Antwi
description: Cybersecurity Professional | Cloud Specialist | Digital Forensics Expert
baseurl: ""
url: ""

# Theme
theme: jekyll-theme-cayman
show_downloads: false
markdown: kramdown

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Social links
social:
  linkedin: noble-antwi-worlanyo
  github: noble-antwi
  email: amnworlanyo@gmail.com

# SEO
author: Noble Antwi
lang: en_US

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Certifications"
    url: "/certifications"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"
